title: ThenVsNowTypography
description: A web site about typography design.
footer_text: Copyright 2021 Katarzyna Matuszewska
header_feature_image: ../uploads/placeholder2.jpg
header_text: ThenVsNow
header_text_color: "#411aaf"
bannerheight: 20vmax
navbarheight: 55px
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
