title: TYPOGRAPHY IN FASHION
description: A web site about typography design in fashion design.
footer_text: Copyright 2021 Katarzyna Matuszewska
header_feature_image: ../uploads/banner.png
header_text: ""
header_text_color: "#cb0076"
bannerheight: 100vh
navbarheight: 55px
logo: ../uploads/logo2.png
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
